---
# tasks file for vector-role
- name: mkdir_for_vector
      file:
        path: "{{ vector_home }}"
        state: directory
      tags: vector_dir
    - name: get_vector_distrib
      get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "./vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
      delegate_to: localhost
    - name: unpack
      unarchive:
        src: "vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ vector_home }}"
        extra_opts: [--strip-components=1]
        remote_src: yes
        creates: "{{ vector_home }}/bin/vector"
      tags: vector_unpack
    - name: template_config
      template:
        src: "template/vector.cfg.j2"
        dest: "{{ vector_home }}"
        backup: True
      register: template_result
      tags: vector_template 
